name: Auto Fork on New Commit

on:
  push:
    branches:
      - master  # 或者你可以选择其他分支

jobs:
  fork:
    runs-on: ubuntu-latest  # 选择运行环境

    steps:
      # 第一步：获取代码
      - name: Checkout the repository
        uses: actions/checkout@v3

      # 第二步：发起 fork 请求
      - name: Fork the repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/fzls/djc_helper/forks
